### PR TITLE
Feature/poet 3 connect to jira api

### PR DESCRIPTION
**Pull request by dxli94**
1. Migrate from Play 2.4.8 -> 2.5.0
2. Change the NLP part structure to cater for Controller class.
3. Use Play Web Service to send async request to JIRA. Can fetch info back according to the ticket number.
4. Read JIRA account and password from a locally held file, rather than hard code.
5. Create a file to store missed query for further improvement.
6. Delete previous redundant files, including files under Httpclient directory and mistakenly commited .DS_Store files.

### CODE REVIEW

**Review by hasanniz — CHANGES_REQUESTED** [review]
Controllers shouldn't have any major logic in them. Move the logic in specific classes and make controllers consume that logic.

Also I like the idea of how you used the properties to fetch username/password.

**Comment by hasanniz** [comment]
Why are there 2,366 files in this branch?

**Comment by dxli94** [comment]
Hi Hasan,

Please cancel this pull request. We have already moved to another branch feature/POET-3-connect-to-JIRA_api-amend. We will create a new pull request once we finalise the work.

Sorry for inconvenient.

Kind regards.
Dongxu

**Comment by hasanniz** [comment]
Cool, thanks.

**Pull request closed without merging**
